### ISSUE TITLE
console error message

### ISSUE THREAD

**Issue by furqon** [frangiskos/mssql#1]
Hi, thank you for your great work. Im trying to follow your documentation in generating error message but somehow I can't produce error message and assign to variable before send back to frontend.

I have unique constrain in my table
```
let col = [];
let val = [];
for (var key in data) {
  col.push(key);
  val.push(data[key]);
}

try {
    const id = await sql.ii(`INSERT INTO ${table} (${col.join(', ')}) VALUES ('${val.join('\', \'')}')`);
    res.json({ 
        id
    });
  } catch (error) {
    res.json({ 
      error
    });
  }
```

The error message is generated in backend, and not in error variable.
<img width="1427" alt="Screen Shot 2020-04-13 at 22 30 54" src="https://user-images.githubusercontent.com/446747/79133685-a270db80-7dd6-11ea-823b-03c81b60013a.png">

**Comment by frangiskos** [comment]
Hi, from the error it looks like that you have column with unique key index
and you are trying to insert a value that already exist (e.g. change
nama-project to something else).

Note that constructing your query this way does not protect you from sql
injections. So make sure you trust the values that you pass to the query. A
better way to write it is by trying to avoid passing the values directly in
query string, and instead pass them as extra parameters to the sql.ii.

e.g. const id = await sql.ii(`INSERT INTO ${table} (${col.join(', ')})
VALUES (${val.map((v, i) => '@P' +  (i+1)).join(',')})`, ...val)

**Comment by furqon** [comment]
yes its sql injection vulnerable, im still in testing phase. 

is there a way to put that error message in error variable, informing about unique constraint?
```
try {
  const id = await sql.ii(`INSERT INTO ${table} (${col.join(', ')}) VALUES ('${val.join('\', \'')}')`);
    console.log(id); 
} catch (error) {
    console.log(error); // <-- here?
}
```

**Comment by frangiskos** [comment]
in catch you should get the full error message as it is returned by the underlying [mssql](https://github.com/tediousjs/node-mssql) library. We don't parse the error message in any way

**Comment by furqon** [comment]
ah, ok then. thank you.
